[zookeeper]
servers = ["zoo1:2181"]
timeout = 6
root-path = "/burrow"

[client-profile.profile]
kafka-version = "2.1.0"
client-id = "docker-client"

[cluster.local]
client-profile = "profile"
class-name = "kafka"
servers = ["kafka1:19092", "kafka1:19093", "kafka1:19094"]
topic-refresh = 10
offset-refresh = 10
groups-reaper-refresh = 30

[consumer.local]
class-name = "kafka"
cluster = "local"
servers = ["kafka1:19092", "kafka1:19093", "kafka1:19094"]
group-denylist = "^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist = ""

[consumer.local_zk]
class-name = "kafka_zk"
cluster = "local"
servers = ["zoo1:2181"]
zookeeper-path = "/local"
zookeeper-timeout = 30
group-denylist = "^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist = ""

[httpserver.default]
address = ":8000"
